### ISSUE TITLE
Cannot find module '../../riot'

### ISSUE THREAD

**Issue by attila** [PabloSichert/isomorphic-proof-of-concept#1]
I get this on npm start:

```
$ npm start

> isomorphic-proof-of-concept@1.1.0 start /private/tmp/isomorphic-proof-of-concept
> node index.js

module.js:339
    throw err;
    ^

Error: Cannot find module '../../riot'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/private/tmp/isomorphic-proof-of-concept/shared/components/app.tag:2:14)
    at Module._compile (module.js:435:26)
    at Object.require.extensions..tag (/private/tmp/isomorphic-proof-of-concept/node_modules/riot/lib/server/index.js:15:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

My environment:

```
$ node -v
v4.2.2
$ npm -v
2.14.7
$ nls
├── babel@5.8.29
├── babelify@6.4.0
├── browserify@11.2.0
├── express@4.13.3
├── gulp@3.9.0
├── nunjucks@2.1.0
├── page@1.6.4
├── redux@3.0.4
├── riot@2.3.0
├── riotify@0.1.2
└── vinyl-source-stream@1.1.0
```

**Comment by pablosichert** [comment]
Hi and thank you for reporting the issue and your system info!

On a similar project someone reported the same error appearing with Riot after upgrading from node 4.2.1 to 4.2.2. I will have a look at the issue and probably forward this to the guys from Riot!

**Comment by pablosichert** [comment]
I just figured out the problem is caused by Riot 2.2.4 -> 2.3.0, 2.2.4 works on either version of node.

**Comment by pablosichert** [comment]
Well, [this issue](https://github.com/riot/riot/issues/1316) seems related. :smile:

So the options for now would be rolling back to Riot 2.2.4 or waiting for the 2.3.1 release.

**Comment by attila** [comment]
Thanks a lot Pablo, downgrading riot to 2.2.4 works like a charm!
